spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
eureka:
  client:
    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      # defaultZone: http://localhost:8888/eureka
      # 将两个Eureka的地址都加入，这样就算有一个Eureka挂掉，也能完成注册
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka
feign:
  circuitbreaker:
    # 开启OpenFeign熔断降级
    enabled: true
management:
  endpoints:
    web:
      exposure:
        # Actuator添加暴露
        #http://localhost:8301/actuator/hystrix.stream
        include: '*'